barateiro:
  dev:
    ApiIntegracaoB2b: http://api-integracao-barateiro.dev-b2b.net
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.dev-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.barateiro.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  hlg:
    ApiIntegracaoB2b: http://b2b-servico-barateiro.hlg-b2b.net/api-integracao-b2b
    url_carrinho: https://carrinho.barateiro.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.hlg-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.barateiro.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  stg:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.barateiro.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.stage-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.barateiro.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  prd:
    ApiIntegracaoB2b: ''
    url_bandeira: http://www.barateiro.com.br
    url_carrinho: https://carrinho.barateiro.com.br
    url_carrinho_multicanalidade: ''
    ApiMarketing: https://api-b2b.admin.com.br/ApiNova
    ApiMaisPontos: http://api-b2b.maispontos.com.br
    ApiWorkflow: https://workflow.api-cnova.com.br/v1
    ApiSeguranca: http://seguranca.nova.com
    ApiLoja: http://api-b2b.admin.com.br/ApiLoja
    ApiGateway: https://api-b2c.barateiro.com.br/Gateway/V1
    ApiCartaoPresente: http://cartaopresente.com.br
    ApiCotadorB2B: https://cotador-b2b.api-cnova.com.br/v1
    ApiB2C: https://api-b2c.barateiro.com.br
    ApiCarneOnline: ''
    ApiCorporativo: http://api-b2b.admin.com.br/ApiCorp
    ApiCatalogo: https://api-b2b.admin.com.br/ApiCatalogo
    ApiAdminB2b: https://admin.b2b.com.br/Api
    ApiRecomendacao: ''
casasbahia:
  dev:
    ApiIntegracaoB2b: http://api-integracao-casasbahia.dev-b2b.net
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.dev-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.casasbahia.com.br
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  hlg:
    ApiIntegracaoB2b: http://b2b-servico-casasbahia.hlg-b2b.net/api-integracao-b2b
    url_carrinho: https://carrinho.casasbahia.com.br
    url_carrinho_multicanalidade: http://carrinho.casasbahiahlg.net
    url_bandeira: http://www.casasbahiahlg.net
    ApiMarketing: http://api-marketing.hlg-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.casasbahia.com.br
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  stg:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.casasbahia.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.stage-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.casasbahia.com.br
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  prd:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.casasbahia.com.br
    url_carrinho_multicanalidade: 'http://carrinho.casasbahia.com.br'
    url_bandeira: http://www.casasbahia.com.br
    ApiMarketing: https://api-b2b.admin.com.br/ApiNova
    ApiMaisPontos: http://api-b2b.maispontos.com.br
    ApiWorkflow: https://workflow.api-cnova.com.br/v1
    ApiSeguranca: http://seguranca.nova.com
    ApiLoja: http://api-b2b.admin.com.br/ApiLoja
    ApiGateway: https://api-b2c.casasbahia.com.br/Gateway/V1
    ApiCartaoPresente: http://cartaopresente.com.br
    ApiCotadorB2B: https://cotador-b2b.api-cnova.com.br/v1
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.casasbahia.com.br
    ApiCorporativo: http://api-b2b.admin.com.br/ApiCorp
    ApiCatalogo: https://api-b2b.admin.com.br/ApiCatalogo
    ApiAdminB2b: https://admin.b2b.com.br/Api
    ApiRecomendacao: https://rec.casasbahia.com.br/recommender
extra:
  dev:
    ApiIntegracaoB2b: http://api-integracao-extra.dev-b2b.net
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.dev-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.extra.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  hlg:
    ApiIntegracaoB2b: http://b2b-servico-extra.hlg-b2b.net/api-integracao-b2b
    url_carrinho: https://carrinho.extra.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.hlg-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.extra.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  stg:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.extra.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.stage-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.extra.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  prd:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.extra.com.br
    url_bandeira: http://www.extra.com.br
    url_carrinho_multicanalidade: ''
    ApiMarketing: https://api-b2b.admin.com.br/ApiNova
    ApiMaisPontos: http://api-b2b.maispontos.com.br
    ApiWorkflow: https://workflow.api-cnova.com.br/v1
    ApiSeguranca: http://seguranca.nova.com
    ApiLoja: http://api-b2b.admin.com.br/ApiLoja
    ApiGateway: https://api-b2c.extra.com.br/Gateway/V1
    ApiCartaoPresente: http://cartaopresente.com.br
    ApiCotadorB2B: https://cotador-b2b.api-cnova.com.br/v1
    ApiB2C: https://api-b2c.extra.com.br
    ApiCarneOnline: ''
    ApiCorporativo: http://api-b2b.admin.com.br/ApiCorp
    ApiCatalogo: https://api-b2b.admin.com.br/ApiCatalogo
    ApiAdminB2b: https://admin.b2b.com.br/Api
    ApiRecomendacao: https://rec.extra.com.br/recommender
hp:
  dev:
    ApiIntegracaoB2b: http://api-integracao-hp.dev-b2b.net
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.dev-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.hp.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  hlg:
    ApiIntegracaoB2b: http://b2b-servico-hp.hlg-b2b.net/api-integracao-b2b
    url_carrinho: https://carrinho.lojahp.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.hlg-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.hp.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  stg:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.lojahp.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.stage-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.hp.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  prd:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.lojahp.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: https://api-b2b.admin.com.br/ApiNova
    ApiMaisPontos: http://api-b2b.maispontos.com.br
    ApiWorkflow: https://workflow.api-cnova.com.br/v1
    ApiSeguranca: http://seguranca.nova.com
    ApiLoja: http://api-b2b.admin.com.br/ApiLoja
    ApiGateway: https://api-b2c.lojahp.com.br/Gateway/V1
    ApiCartaoPresente: http://cartaopresente.com.br
    ApiCotadorB2B: https://cotador-b2b.api-cnova.com.br/v1
    ApiB2C: https://api-b2c.hp.com.br
    ApiCarneOnline: ''
    ApiCorporativo: http://api-b2b.admin.com.br/ApiCorp
    ApiCatalogo: https://api-b2b.admin.com.br/ApiCatalogo
    ApiAdminB2b: https://admin.b2b.com.br/Api
    ApiRecomendacao: ''
pontofrio:
  dev:
    ApiIntegracaoB2b: http://api-integracao-pontofrio.dev-b2b.net
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.dev-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.pontofrio.com.br
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  hlg:
    ApiIntegracaoB2b: http://b2b-servico-pontofrio.hlg-b2b.net/api-integracao-b2b
    url_carrinho: https://carrinho.pontofrio.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.hlg-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.pontofrio.com.br
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  stg:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.pontofrio.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.stage-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.pontofrio.com.br
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  prd:
    ApiIntegracaoB2b: ''
    url_carrinho: https://carrinho.pontofrio.com.br
    url_carrinho_multicanalidade: ''
    url_bandeira: http://www.pontofrio.com.br
    ApiMarketing: https://api-b2b.admin.com.br/ApiNova
    ApiMaisPontos: http://api-b2b.maispontos.com.br
    ApiWorkflow: https://workflow.api-cnova.com.br/v1
    ApiSeguranca: http://seguranca.nova.com
    ApiLoja: http://api-b2b.admin.com.br/ApiLoja
    ApiGateway: https://api-b2c.pontofrio.com.br/Gateway/V1
    ApiCartaoPresente: http://cartaopresente.com.br
    ApiCotadorB2B: https://cotador-b2b.api-cnova.com.br/v1
    ApiCarneOnline: https://carneonline.casasbahia.com.br/CarneOnline
    ApiB2C: https://api-b2c.pontofrio.com.br
    ApiCorporativo: http://api-b2b.admin.com.br/ApiCorp
    ApiCatalogo: https://api-b2b.admin.com.br/ApiCatalogo
    ApiAdminB2b: https://admin.b2b.com.br/Api
    ApiRecomendacao: https://rec.pontofrio.com.br/recommender
aoc:
  dev:
    ApiIntegracaoB2b: ''
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.dev-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.aoc.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  hlg:
    ApiIntegracaoB2b: ''
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.hlg-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.aoc.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  stg:
    ApiIntegracaoB2b: ''
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: http://api-marketing.stage-b2b.net
    ApiMaisPontos: ''
    ApiWorkflow: ''
    ApiSeguranca: ''
    ApiLoja: ''
    ApiGateway: ''
    ApiCartaoPresente: ''
    ApiCotadorB2B: ''
    ApiB2C: https://api-b2c.aoc.com.br
    ApiCarneOnline: ''
    ApiCorporativo: ''
    ApiCatalogo: ''
    ApiAdminB2b: ''
    ApiRecomendacao: ''
  prd:
    ApiIntegracaoB2b: ''
    url_carrinho: ''
    url_carrinho_multicanalidade: ''
    url_bandeira: ''
    ApiMarketing: https://api-b2b.admin.com.br/ApiNova
    ApiMaisPontos: http://api-b2b.maispontos.com.br
    ApiWorkflow: https://workflow.api-cnova.com.br/v1
    ApiSeguranca: http://seguranca.nova.com
    ApiLoja: http://api-b2b.admin.com.br/ApiLoja
    ApiGateway: https://api-b2c.aocloja.com.br/Gateway/V1
    ApiCartaoPresente: http://cartaopresente.com.br
    ApiCotadorB2B: https://cotador-b2b.api-cnova.com.br/v1
    ApiB2C: https://api-b2c.aoc.com.br
    ApiCarneOnline: ''
    ApiCorporativo: http://api-b2b.admin.com.br/ApiCorp
    ApiCatalogo: https://api-b2b.admin.com.br/ApiCatalogo
    ApiAdminB2b: https://admin.b2b.com.br/Api
    ApiRecomendacao: ''
